### PR TITLE
Changed Websocked Server to Production

### PR DESCRIPTION
**Pull request by Tert0**
**Description**
Changed Websocket Server to Production Server
**Issue**
You cant do anything because the Test Server is Offline

### CODE REVIEW

**Review by MarcelCoding — APPROVED** [review]

**Comment by JannikEmmerich** [comment]
Don't know if we should do that, because the server being offline ist just a temporary state.

**Comment by Tert0** [comment]
But it will be a long time before version 3

**Review by JannikEmmerich — CHANGES_REQUESTED** [review]
@MaxiHuHe04 should decide that, but I don't think, we should to it.

**Comment by Tert0** [comment]
> @MaxiHuHe04 should decide that, but I don't think, we should to it.

Should I close this Pull Request?

**Pull request closed without merging**
