### PR TITLE
Disable Format on Save in VS Code

### PR DESCRIPTION
**Pull request by Tert0**
**Description**
Disable Format on Save in VS Code

**Testing Instructions**
Save an File in VS Code

### CODE REVIEW

**Comment by Tert0** [comment]
Why are all my old Commits from the master Branch here?

**Comment by JannikEmmerich** [comment]
> Why are all my old Commits from the master Branch here?

Because you created your new branch from the master branch.

**Comment by Tert0** [comment]
Is that bad?

**Review by JannikEmmerich — APPROVED** [review]

**Review by MarcelCoding — COMMENTED** [review]
I think the commit should be formatted. We should improve the formatter configuration of vscode or use prettier.

**Comment by MarcelCoding** [comment]
See #218

**Comment by Tert0** [comment]
@MarcelCoding Yes i saw. But cant use VS Code correctly with that Auto Format.

**Pull request closed without merging**
