### PR TITLE
Issue/39 autocomplete

### PR DESCRIPTION
**Pull request by Akida31**
**Description**
The autocompletion searches also in the history. Also changed how commands are hidden (attribute instead of excluding by name).

**Issue**
#39 (probably don't close it -> Addititional Notes)

**Testing Instructions**
- write something in the terminal
- write the beginning again and press [Tab]

**Additional Notes**
- fixed typo
- Should there also a hint about what will be completed? (like in fish)

**Merge Instructions** (@MarcelCoding)
Please squash this PR

### CODE REVIEW

**Comment by JannikEmmerich** [comment]
> Please change the commit message `removed hardcoded hidden commands` into `removed hardcoded hidden commands (#39)`.

Since the commit has nothing to do with the issue I wouldn't do that.

**Comment by MarcelCoding** [comment]
@Akida31 please update/rebase your branch

**Comment by Akida31** [comment]
@MarcelCoding 
I had to recreate the PR because after a half year I deleted my fork and because of that I wasn't able to rebase this PR.

**Comment by Akida31** [comment]
Rebased version: #212

**Pull request closed without merging**
